--1 to check nuber of customers  793
select count(distinct customer_id) from [dbo].[cleaned_superstore]

--2 to check number of orders generated by each customer
select customer_id,count(order_id) as orders_of_each_customer
from [dbo].[cleaned_superstore]
group by customer_id
order by orders_of_each_customer desc

--3 to check average sales generated by each customer
select customer_id,round(avg(sales),2) as avg_sales_by_customer
from [dbo].[cleaned_superstore]
group by customer_id
order by avg_sales_by_customer desc

--4 top 10 customers
select top 10 customer_id,sum(sales) as total_sales
from [dbo].[cleaned_superstore]
group by customer_id
order by total_sales desc

--5 customers contributing to negative profit
select customer_id,region,sum(profit) as total_profits
from [dbo].[cleaned_superstore]
group by customer_id,region

--6 No of orders generated per year
select order_year,count(order_id) no_of_orders
from [dbo].[cleaned_superstore]
group by order_year
order by no_of_orders desc
order by total_profits

--7 to check yearwise orders for each sub category in orders
SELECT order_year, category, sub_category,
COUNT(order_id) AS total_orders
FROM [dbo].[cleaned_superstore]
GROUP BY order_year, category, sub_category;

--8 to check which is sold more in each season 
select season,sub_category,count(order_id) as total_orders
FROM [dbo].[cleaned_superstore]
group by season,sub_category

--9 To check orders per season
SELECT season, COUNT(order_id) AS total_orders
FROM [dbo].[cleaned_superstore]
GROUP BY season
ORDER BY total_orders DESC;

--10 to check change in orders count year by year
SELECT 
    order_year,
    COUNT(DISTINCT order_id) AS total_orders,
    
    COUNT(DISTINCT order_id) - 
    LAG(COUNT(DISTINCT order_id)) OVER (ORDER BY order_year) 
    AS order_difference

FROM cleaned_superstore
GROUP BY order_year
ORDER BY order_year;

--11 to analyse change in sales growth year after year
WITH yearly_sales AS (
    SELECT 
        order_year,
        SUM(sales) AS total_sales
    FROM cleaned_superstore
    GROUP BY order_year
)

SELECT 
    order_year,
    total_sales,
    
    total_sales - LAG(total_sales) OVER (ORDER BY order_year) AS sales_difference,
    
    ROUND(
        (total_sales - LAG(total_sales) OVER (ORDER BY order_year)) * 100.0 
        / LAG(total_sales) OVER (ORDER BY order_year), 2
    ) AS growth_percentage

FROM yearly_sales
ORDER BY order_year;

--12 if there is a sales drop frm 2014 to 2015, which region is having it
--I observed significant drop in south region in "technology category"
SELECT 
    category,
    order_year,
    SUM(sales) AS total_sales
FROM cleaned_superstore
WHERE region='South' and order_year IN (2014, 2015)
GROUP BY category, order_year
ORDER BY category, order_year;


--13 to check how discounts impacting the profits
SELECT 
    category,
    AVG(discount) AS avg_discount,
    SUM(profit) AS total_profit
FROM cleaned_superstore
GROUP BY category
ORDER BY avg_discount DESC;

--14 Profit margin by sub-category
SELECT sub_category,
       ROUND(SUM(profit) / NULLIF(SUM(sales), 0) * 100, 2) AS profit_margin_pct
FROM cleaned_superstore
GROUP BY sub_category
ORDER BY profit_margin_pct ASC;

--15 Discount threshold analysis — where does profit turn negative?
SELECT
    CASE
        WHEN discount = 0 THEN '0%'
        WHEN discount <= 0.10 THEN '1-10%'
        WHEN discount <= 0.20 THEN '11-20%'
        WHEN discount <= 0.40 THEN '21-40%'
        ELSE '40%+'
    END AS discount_bucket,
    COUNT(*) AS orders,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(AVG(profit), 2) AS avg_profit
FROM cleaned_superstore
GROUP BY
    CASE
        WHEN discount = 0 THEN '0%'
        WHEN discount <= 0.10 THEN '1-10%'
        WHEN discount <= 0.20 THEN '11-20%'
        WHEN discount <= 0.40 THEN '21-40%'
        ELSE '40%+'
    END
ORDER BY discount_bucket;

--16 . Customer segmentation (Consumer vs Corporate vs Home Office)
SELECT segment,
       COUNT(DISTINCT customer_id) AS customers,
       ROUND(SUM(sales), 2) AS total_sales,
       ROUND(SUM(profit), 2) AS total_profit,
       ROUND(AVG(discount), 3) AS avg_discount
FROM cleaned_superstore
GROUP BY segment
ORDER BY total_profit DESC;

--17  Ship mode vs profitability
SELECT ship_mode,
       COUNT(DISTINCT order_id) AS orders,
       ROUND(SUM(sales), 2) AS total_sales,
       ROUND(SUM(profit), 2) AS total_profit,
       ROUND(AVG(profit), 2) AS avg_profit_per_order
FROM cleaned_superstore
GROUP BY ship_mode
ORDER BY avg_profit_per_order DESC;

--18Repeat vs one-time customers
SELECT
    CASE WHEN order_count = 1 THEN 'One-time'
         WHEN order_count <= 5 THEN 'Occasional (2-5)'
         ELSE 'Frequent (6+)'
    END AS customer_type,
    COUNT(*) AS customer_count,
    ROUND(AVG(total_sales), 2) AS avg_sales_per_customer
FROM (
    SELECT customer_id,
           COUNT(DISTINCT order_id) AS order_count,
           SUM(sales) AS total_sales
    FROM cleaned_superstore
    GROUP BY customer_id
) t
GROUP BY
    CASE WHEN order_count = 1 THEN 'One-time'
         WHEN order_count <= 5 THEN 'Occasional (2-5)'
         ELSE 'Frequent (6+)'
    END;

--19State-level performance
SELECT state, region,
       ROUND(SUM(sales), 2) AS total_sales,
       ROUND(SUM(profit), 2) AS total_profit,
       ROUND(SUM(profit)/NULLIF(SUM(sales),0)*100, 2) AS margin_pct
FROM cleaned_superstore
GROUP BY state, region
ORDER BY total_profit ASC;

--20 Top loss-making products 
SELECT TOP 10 product_name, sub_category,
       ROUND(SUM(profit), 2) AS total_profit,
       COUNT(order_id) AS times_ordered
FROM cleaned_superstore
GROUP BY product_name, sub_category
ORDER BY total_profit ASC;